# Generated by Django 6.1 on 2026-08-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='consulta',
            name='consulta_profissional_data_horario_unicos',
        ),
        migrations.AddConstraint(
            model_name='consulta',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'cancelada'), _negated=True), fields=('profissional', 'data', 'horario'), name='consulta_profissional_data_horario_unicos'),
        ),
    ]
