# Generated by Django 6.1 on 2026-08-06 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('last_name', models.TextField(max_length=40, verbose_name='Sobrenome')),
            ],
            options={
                'verbose_name': 'Paciente',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20, verbose_name='Nome')),
                ('last_name', models.TextField(max_length=40, verbose_name='Sobrenome')),
            ],
            options={
                'verbose_name': 'Paciente',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Título')),
            ],
            options={
                'verbose_name': 'Qualificação',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, verbose_name='Assunto')),
                ('date', models.DateField(verbose_name='Data')),
                ('time', models.TimeField(verbose_name='Hora')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Detalhes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
                ('medic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='appointments.medic', verbose_name='Profissional')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='appointments.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Consulta',
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='MedicQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aquired_at', models.DateField(verbose_name='Adquirida em')),
                ('medic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.medic')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.qualification')),
            ],
        ),
        migrations.AddField(
            model_name='medic',
            name='qualifications',
            field=models.ManyToManyField(related_name='medics', through='appointments.MedicQualification', to='appointments.qualification'),
        ),
    ]
