# Generated by Django 6.1 on 2026-08-06 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medic',
            options={'ordering': ['name'], 'verbose_name': 'Profissional', 'verbose_name_plural': 'Profissionais'},
        ),
        migrations.AlterModelOptions(
            name='medicqualification',
            options={'ordering': ['medic'], 'verbose_name': 'Profissionis e Qualificações'},
        ),
        migrations.AlterModelOptions(
            name='qualification',
            options={'ordering': ['name'], 'verbose_name': 'Tipo de Qualificação', 'verbose_name_plural': 'Tipos de Qualificação'},
        ),
    ]
