# Generated by Django 6.1 on 2026-08-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['date', 'time'], 'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultas'},
        ),
        migrations.AlterModelOptions(
            name='medic',
            options={'ordering': ['name'], 'verbose_name': 'Profissional', 'verbose_name_plural': 'Profissionais'},
        ),
        migrations.AlterModelOptions(
            name='medicqualification',
            options={'ordering': ['qualification'], 'verbose_name': 'Qualificação do Profissional', 'verbose_name_plural': 'Qualificações dos Profissionais'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['name'], 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterModelOptions(
            name='qualification',
            options={'ordering': ['name'], 'verbose_name': 'Qualificação', 'verbose_name_plural': 'Qualificações'},
        ),
        migrations.AddField(
            model_name='medic',
            name='email',
            field=models.EmailField(default='dummy@nothing.nothing', max_length=254, verbose_name='E-Mail'),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(default='dummy@nothing.nothing', max_length=254, verbose_name='E-Mail'),
        ),
    ]
