# Generated by Django 6.1 on 2026-08-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_medic_options_alter_medicqualification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medic',
            name='last_name',
            field=models.CharField(max_length=40, verbose_name='Sobrenome'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(max_length=40, verbose_name='Sobrenome'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Nome'),
        ),
    ]
