# Generated by Django 6.1 on 2026-08-10 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_options_alter_medic_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medic',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='E-Mail'),
        ),
    ]
