# Generated by Django 6.1 on 2026-08-06 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_medic_last_name_alter_patient_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicqualification',
            name='medic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.medic', verbose_name='Profissional'),
        ),
        migrations.AlterField(
            model_name='medicqualification',
            name='qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.qualification', verbose_name='Qualificação'),
        ),
    ]
